name: Deploy Website

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'

    - run: yarn --ci
    - run: yarn build

    - name: Commit build
      uses: EndBug/add-and-commit@v9
      with:
        add: 'docs'
        message: '🔨 Build (automatic)'
        commit: --signoff
        committer_name: Automation